export const GET_STATIC_PAGE = "GET_STATIC_PAGE";
export const RESPONSE_STATUS = "RESPONSE_STATUS";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";
export const CHECKOUT = "CHECKOUT";
export const CHECKOUT_BUYNOW = "CHECKOUT_BUYNOW";
export const CHECKOUT_EMPTY = "CHECKOUT_EMPTY";
